### ISSUE TITLE
When to add consensus groups

### ISSUE THREAD

**Issue by cs-victor-nascimento** [skirino/raft_fleet#1]
Hi! First of all, thanks for your work.

I've been trying to study Raft and how to replicate state in a cluster in a sane way. I'm following your README. Though it is very simple and direct, I am feeling a bit lost with the consensus group concept.

The point I don't quite get is the criteria for adding consensus groups. I'm still trying to understand the whole raft algorithm but I guess this is a bit too simplified in the README. I've seen that you describe a 4 node cluster with 2 zones with 5 consensus groups that use 3 replicas configuration for an Int value

What is the recommended configuration for groups? One per node (but then again you added one more than the node count)? Could you explain it a bit more?

Sorry for the "question" issue... if this is not the place to ask such questions, please tell me where I can post it and I'll do it.

Thanks once again!

**Comment by skirino** [comment]
Hi,

I forgot to define the term "consensus group" in the README. Sorry for your confusion.
A "consensus group" here means:
a group of Erlang processes that replicate an Erlang/Elixir value and provide a [linearizable](https://en.wikipedia.org/wiki/Linearizability) access to the value.
Usually a consensus group consists of 3 processes to tolerate 1 member failure.

I think you've lost in how raft_fleet organizes processes in the cluster.
In this regard please look at [this figure](https://github.com/basho/riak_ensemble/blob/develop/doc/cluster.png) of [`riak_ensemble`](https://github.com/basho/riak_ensemble).
Process placement strategy of `raft_fleet` is basically the same as that of riak_ensemble (read "ensemble" in the figure as "consensus group").
Also, as each consensus member process has the same name as the consensus group, inspecting the running processes using e.g. `Process.whereis(:consensus1)`, `RaftedValue.status({:consensu1, node1})` would be helpful in understanding what's going on under the hood.

For overall design of raft_fleet, [slides I made to explain `raft_fleet`](https://skirino.github.io/slides/raft_fleet.html#/) might be helpful.
I hope this answers your question, but please feel free to ask more.

**Comment by cs-victor-nascimento** [comment]
Thanks a lot for your comment. It really helped me!

I'm testing several configurations for a distributed local setup. Once I get the hang of it I can open a PR adding some more info to the README. The links you have here are really helpful.

One question: do you have the video of the presentaion?

**Comment by skirino** [comment]
The presentation I gave in [tokyo.ex #7](https://kbkz.connpass.com/event/46153/) was in Japanese, although the slides are written in English.
There was a live streaming of the presentation but I don't know the video is now available or not.

**Comment by cs-victor-nascimento** [comment]
Thanks a lot! In Japanese only with subtitles for me (maybe in the future :)).

Will be closing the issue as you've explained it here, but I think those links could be in the README of the project.

**Comment by cs-victor-nascimento** [comment]
Oooops... just noticed you've already added them. So, skip me bothering you on the last comment.

Thanks once again.
