### ISSUE TITLE
Slow readding group after restart

### ISSUE THREAD

**Issue by liveforeverx** [skirino/raft_fleet#3]
Hi!

I have some questions about fault tolerance of `raft_fleet`.

I'm starting cluster (3 nodes), using `RaftKV` and Instructions there:

Starting looks like: 

```elixir
for n <- [:'test1@dar', :'test2@dar', :'test3@dar'], do:  Node.connect(n)
RaftFleet.activate("test")
:ok = RaftKV.init()
merge_policy = %SplitMergePolicy{max_shards: 32, max_keys_per_shard: 500}
RaftKV.register_keyspace(name, [], __MODULE__, nil, merge_policy)
```

Test: kill node and start again, I always kill one node to not break a quorum, but sometime, it still breakes a complete cluster. For example, I get this:

Killing node1, I get on node3: 

```elixir
19:01:41.738 [error] Discarding message {'$gen_cast',#{'__struct__'=>'Elixir.RaftedValue.RPC.RequestVoteRequest',candidate_pid=><0.193.0>,last_log=>{1,116},replacing_leader=>false,term=>25}} from <0.193.0> to <0.184.0> in an old incarnation (1) of this node (2)
```

On node2:
```elixir
19:01:51.423 [warn]  querying all consensus groups failed: :no_leader
```

And cluster never returns to a working state.

**Comment by liveforeverx** [comment]
It seems to be not a problem of a raft, but problem of beam for too quick restarts.

**Comment by liveforeverx** [comment]
Another problem(cluster restarted, so I killed one node), than after some time, it writes

```
19:21:55.157 [error] all members of clastero_0 have failed; removing the consensus group as a last resort: :ok
```

And I can't write anything with 2 node cluster. So, I still didn't violate the condition of quorum.

**Comment by liveforeverx** [comment]
It happens, if I kill leader, it seems, that if cluster of 3 nodes loses leader, it can't work anymore, but if it loses not a leader, it still works.

**Comment by skirino** [comment]
Hi,

Could you describe the detailed steps to reproduce this issue?
Also do you know at which step things went wrong: when you killed an ErlangVM node, or when you restarted the node?
Watching the status of consensus group processes (by e.g. `RaftedValue.status(:consensus1)`) might be helpful.

**Comment by liveforeverx** [comment]
Thanks for answer!

`RaftedValue.status(:consensus1)` helped a lot to clarify. I was too quick in all operations. For example, the first situation, where killing leader broke a cluster, than not all members have replicated, from 3 nodes the raft group wasn't ready on all nodes, that why it doesn't worked.

Now, I'm checking, that every change reflected in `RaftedValue.status(:consensus1)`, but it takes
at least 4 minutes to take the change.

2 minutes before unresponsive follower will be removed:

```elixir
%{
  config: %RaftedValue.Config{
    communication_module: RaftedValue.RemoteMessageGateway,
    data_module: JustAnInt,
    election_timeout: 1000,
    election_timeout_clock_drift_margin: 1000,
    heartbeat_timeout: 200,
    leader_hook_module: RaftedValue.LeaderHook.NoOp,
    max_retained_command_results: 100
  },
  current_term: 4,
  from: #PID<0.201.0>,
  leader: #PID<0.201.0>,
  members: [#PID<0.201.0>, #PID<15845.205.0>, #PID<15860.218.0>],
  state_name: :leader,
  unresponsive_followers: [#PID<15860.218.0>]
}
```

Restarted node at `10:28:28`, than I see:

```elixir
10:30:28.948 [info]  a member (#PID<0.199.0>) of consensus1 is definitely dead; remove it from the group: :ok
10:32:28.942 [info]  migrating leader of consensus1 in test1@dar to the member in this node: :ok
```

It needs 2 minutes to remove member from a group and it needs 2 minutes more to add restarted node to a group again.
For empty cluster, rolling update will take at least: 4 * n nodes minutes. (12 minutes for empty 3 node cluster) Are there any configuration option to make this time frame smaller?

**Comment by liveforeverx** [comment]
@skirino Probably, I can try to twig `:balancing_interval` if it helps to reduce time of restarts than.

**Comment by skirino** [comment]
If what you want to achieve is code upgrade, [this](https://github.com/skirino/raft_fleet#deployment-notes) can be helpful.
I'd avoid shutdown-and-restart an ErlangVM node for code upgrade, as it temporarily makes the cluster less resilient to accidental death of other running node (but it depends on your infrastructure).
`RaftFleet.deactivate/0` doesn't immediately remove the running processes as documented [here](https://hexdocs.pm/raft_fleet/RaftFleet.html#deactivate/0).

**Comment by liveforeverx** [comment]
Yes, right, it only relocates leader right after to another node, as I saw. Anyway, if there is no possibility to reduce minimal time from 4 minutes to something smaller for empty cluster, I will live with that and document this behaviour.

Thanks!

I will close issue for now, as it is not a bug, but intended behaviour.

**Comment by liveforeverx** [comment]
Using this configuration:

```
config :raft_fleet,
  node_purge_reconnect_interval: 15_000,
  balancing_interval: 15_000
```

I can reach shorter interval, so it is possible to change by configuration.
